apiVersion: v1
kind: Template
labels:
  template: license-analysis
metadata:
  name: license-analysis
  annotations:
    description: license-analysis
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: license-analysis
    name: license-analysis
  spec:
    replicas: 1
    selector:
      service: license-analysis
    template:
      metadata:
        labels:
          service: license-analysis
      spec:
        containers:
        - command:
          - /bin/entrypoint.sh
          env:
          - name: DEPLOYMENT_PREFIX
            valueFrom:
              configMapKeyRef:
                name: bayesian-config
                key: deployment-prefix
          - name: SERVICE_PORT
            value: "6162"
          - name: SERVICE_TIMEOUT
            value: "900"
          name: license-analysis
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          ports:
          - containerPort: 6162
          livenessProbe:
            httpGet:
              path: /
              port: 6162
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 6162
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 15
          resources:
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: license-analysis
    name: license-analysis
  spec:
    ports:
    - port: 6162
      targetPort: 0
    selector:
      service: license-analysis

parameters:
- description: CPU request
  displayName: CPU request
  required: true
  name: CPU_REQUEST
  value: "3.5"

- description: CPU limit
  displayName: CPU limit
  required: true
  name: CPU_LIMIT
  value: "3.5"

- description: Memory request
  displayName: Memory request
  required: true
  name: MEMORY_REQUEST
  value: "512Mi"

- description: Memory limit
  displayName: Memory limit
  required: true
  name: MEMORY_LIMIT
  value: "512Mi"

- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "registry.devshift.net"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "license-analysis-image"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"
